import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/global/NavBar";
import Footer from "@/components/global/Footer";
import { ToastContainer } from "@/components/ui/toast";
import SmoothScroll from "@/components/ui/Scroll/SmoothScroll";
import ScrollProgress from "@/components/ui/Scroll/ScrollProgress";
import ScrollToTop from "@/components/ui/Scroll/ScrollToTop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SmoothScroll
          duration={1.1}
          easing="expo"
          wheelMultiplier={1}
          touchMultiplier={1.5}
          disableOnMobile={false}
        >
          {/* scroll progress bar at very top */}
          <ScrollProgress />
          <NavBar />
          <ToastContainer position="top-right" />
          {children}
          <Footer />
          {/* back to top button */}
          <ScrollToTop />
        </SmoothScroll>
      </body>
    </html>
  );
}
